### ISSUE TITLE
Add another this person DNE link

### ISSUE THREAD

**Issue by GNU-Linuxer** [paubric/awesome-doesnotexist#9]
This link is: https://generated.photos/

**Comment by paulbricman** [comment]
Nice! Also, it's Hacktoberfest! So make a PR and get closer to winning some open source goodies.

**Comment by GNU-Linuxer** [comment]
Unfortunately I can't create a PR. Additionally, we can add this FRIENDS DNE (https://thispersondoesnotexist.com/friends/) and this OFFICE DNE (https://thispersondoesnotexist.com/office/)
